
tasks:
  - name: prepare
    before: |
      sudo cp -f /workspace/qstag23-de-tutorial/.vscode/QS_Tag_Background.png /usr/share/backgrounds/xfce/xfce-verticals.png
      clear
  - name: install System
    init: |
      yes | pyenv install 3.11.6
      pyenv global 3.11.6
      python -m pip install --upgrade pip
      pip install -r requirements.txt
      pip install --upgrade --pre robotframework
      rfbrowser init
      npx --yes playwright install-deps
  - name: Command
    command: |
      sudo cp -f /workspace/qstag23-de-tutorial/.vscode/QS_Tag_Background.png /usr/share/backgrounds/xfce/xfce-verticals.png
      clear
image: gitpod/workspace-full-vnc
ports:
  - port: 6080
    onOpen: open-preview
    visibility: private
vscode:
  extensions:
    - ms-python.python
    - d-biehl.robotcode
    - bierner.docs-view
    - ms-toolsai.jupyter
    - ms-toolsai.jupyter-keymap
    - ms-toolsai.jupyter-renderers
    - PKief.material-icon-theme
    - mechatroner.rainbow-csv
